# Generated by Django 4.2.30 on 2026-04-08 16:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('psychologist', 'Психолог'), ('manager', 'Менеджер')], default='client', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('manager_notes', models.CharField(blank=True, max_length=300, null=True)),
                ('resolved', models.TextField(blank=True, null=True)),
                ('created', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.client')),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'method',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Platezhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.TextField()),
            ],
            options={
                'db_table': 'platezhi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'problem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('qlick_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на qlick.io')),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Psychologist/')),
            ],
            options={
                'db_table': 'psychologist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PsychologistApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('education', models.CharField(max_length=255, verbose_name='Образование')),
                ('experience', models.CharField(max_length=255, verbose_name='Опыт работы')),
                ('photo', models.BinaryField(blank=True, null=True, verbose_name='Фото (бинарные данные)')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Рассмотрена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
            ],
            options={
                'verbose_name': 'Заявка от психолога',
                'verbose_name_plural': 'Заявки от психологов',
                'db_table': 'psychologist_application',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statusfeedbaack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'statusFeedbaack',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statusplatezh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'statusPlatezh',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statussession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'statusSession',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Technika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'technika',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('feedback', models.ForeignKey(blank=True, db_column='feedback_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_feedback_rel', to='main.feedback')),
                ('platezhi', models.ForeignKey(blank=True, db_column='platezhi_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_platezhi_rel', to='main.platezhi')),
                ('psychologist', models.ForeignKey(db_column='psychologist_id', on_delete=django.db.models.deletion.CASCADE, to='main.psychologist')),
                ('statussession', models.ForeignKey(db_column='statusSession_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session_status_rel', to='main.statussession')),
            ],
            options={
                'db_table': 'session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PsychologistProblem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.problem')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.psychologist')),
            ],
            options={
                'db_table': 'psychologist_problem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PsychologistMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.method')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.psychologist')),
            ],
            options={
                'db_table': 'psychologist_method',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='psychologist',
            name='methods',
            field=models.ManyToManyField(related_name='psychologists', through='main.PsychologistMethod', to='main.method'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='problems',
            field=models.ManyToManyField(related_name='psychologists', through='main.PsychologistProblem', to='main.problem'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platezhi',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='platezhi_session', to='main.session'),
        ),
        migrations.AddField(
            model_name='platezhi',
            name='statusplatezh',
            field=models.ForeignKey(db_column='statusPlatezh_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.statusplatezh'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.manager'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedback_session', to='main.session'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='statusfeedbaack',
            field=models.ForeignKey(db_column='statusFeedbaack_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.statusfeedbaack'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.type'),
        ),
        migrations.CreateModel(
            name='MethodTechnika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.method')),
                ('technika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.technika')),
            ],
            options={
                'unique_together': {('method', 'technika')},
            },
        ),
    ]
