# Generated by Django 4.2.30 on 2026-04-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodtechnika',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='methodtechnika',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.method'),
        ),
        migrations.AlterField(
            model_name='methodtechnika',
            name='technika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.technika'),
        ),
        migrations.AlterField(
            model_name='psychologistproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.problem'),
        ),
        migrations.AlterField(
            model_name='psychologistproblem',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.psychologist'),
        ),
        migrations.AlterModelTable(
            name='methodtechnika',
            table='method_technika',
        ),
    ]
