# Generated by Django 4.2.30 on 2026-04-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сессии'),
        ),
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время сессии'),
        ),
    ]
