# Generated by Django 4.2.30 on 2026-04-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_session_date_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='selected_methods',
            field=models.JSONField(blank=True, default=list, verbose_name='Методы и техники (JSON)'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
