# Generated by Django 4.2.30 on 2026-04-12 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_psychologist_selected_methods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('отзыв', 'Отзыв'), ('пожелание', 'Пожелание'), ('жалоба', 'Жалоба')], max_length=20, verbose_name='Тип обратной связи')),
                ('description', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_feedback_set', to='main.session', verbose_name='Сессия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обратная связь от клиента',
                'verbose_name_plural': 'Обратная связь от клиентов',
                'db_table': 'client_feedback',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='feedback',
            field=models.ForeignKey(blank=True, db_column='feedback_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_feedback_rel', to='main.clientfeedback'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
