# Generated by Django 4.2.30 on 2026-04-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_clientfeedback_alter_session_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodtechnika',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.method'),
        ),
        migrations.AlterField(
            model_name='methodtechnika',
            name='technika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.technika'),
        ),
        migrations.AlterField(
            model_name='platezhi',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platezhi_session', to='main.session'),
        ),
        migrations.AlterField(
            model_name='platezhi',
            name='statusplatezh',
            field=models.ForeignKey(db_column='statusPlatezh_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.statusplatezh'),
        ),
        migrations.AlterField(
            model_name='psychologistmethod',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.method'),
        ),
        migrations.AlterField(
            model_name='psychologistmethod',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.psychologist'),
        ),
        migrations.AlterField(
            model_name='session',
            name='statussession',
            field=models.ForeignKey(db_column='statusSession_id', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_status_rel', to='main.statussession'),
        ),
    ]
